### ISSUE TITLE
Increase Font Size of Room Code on Trivalry Host Screen

### ISSUE THREAD

**Issue by chase-saca** [partyfishgames/partyfish#49]
Increase the font size of the room code for the Trivalry game while the host is waiting for players to join. This fix will increase readability for players. 

The change should be in the file `/client/src/components/Trivalry/HostPage/index.tsx`.

<img width="1095" alt="Screen Shot 2022-04-13 at 3 45 52 PM" src="https://user-images.githubusercontent.com/62680185/163258326-95a6f614-ae97-4ee7-ba45-eaea1ccee259.png">

**Comment by chase-saca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make Room Code Bigger on Host Waiting Screen](https://trello.com/c/jLgTcx4i/127-make-room-code-bigger-on-host-waiting-screen)

**Comment by fkery** [comment]
#50
