### ISSUE TITLE
Form Validation - Ensure room code textfield has no more than 4 letters

### ISSUE THREAD

**Issue by jgordley** [partyfishgames/partyfish#7]
We need to ensure that a room code is only up to 4 letters long, so the text field must have a limit of 4 characters to be entered
![roomcode](https://user-images.githubusercontent.com/24211938/155201422-7dd53c2d-0c93-4a88-b755-1308d2ffa11c.JPG)
This can be done by either 
* Accessing the textfield characters property
* Or some state logic with the `handleRoomCodeChange` function in client/src/components/Homepage/index.tsx

**Comment by jgordley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Force room code input to only have 4 letters](https://trello.com/c/8VbyL8WL/52-force-room-code-input-to-only-have-4-letters)

**Comment by duncanjpark** [comment]
#51 pull request for change to handleRoomCodeChange function that limits length of input to 4.
